const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Particles,
		C3.Plugins.Mouse,
		C3.Plugins.Audio
	];
};
self.C3_JsPropNameTable = [
	{bg: 0},
	{moreGames: 0},
	{settingsIcon: 0},
	{home: 0},
	{audioOn: 0},
	{fruity_world: 0},
	{arcade_mode: 0},
	{splashScreen: 0},
	{Touch: 0},
	{Text: 0},
	{audioOff: 0},
	{Text2: 0},
	{Button5: 0},
	{Text3: 0},
	{Button2: 0},
	{ButtonNnn: 0},
	{Button123: 0},
	{Text4y: 0},
	{Text4: 0},
	{Text5: 0},
	{Text6: 0},
	{stage1: 0},
	{stage2: 0},
	{stage3: 0},
	{stage4: 0},
	{stage5: 0},
	{stage6: 0},
	{stage7: 0},
	{stage8: 0},
	{stage9: 0},
	{stage10: 0},
	{stage11: 0},
	{stage12: 0},
	{stage13: 0},
	{stage14: 0},
	{stage15: 0},
	{stage16: 0},
	{stage17: 0},
	{stage18: 0},
	{DragDrop: 0},
	{stage1_fruit: 0},
	{stage1_fruit2: 0},
	{stage1_fruit3: 0},
	{stage1_fruit4: 0},
	{stage2_fruit: 0},
	{stage2_fruit2: 0},
	{stage2_fruit3: 0},
	{stage2_fruit4: 0},
	{stage3_fruit: 0},
	{stage3_fruit2: 0},
	{stage1_fruit1b: 0},
	{stage1_fruit2b: 0},
	{stage1_fruit3b: 0},
	{stage1_fruit4b: 0},
	{stage2_fruit1b: 0},
	{stage2_fruit2b: 0},
	{stage2_fruit3b: 0},
	{stage2_fruit4b: 0},
	{stage3_fruit1b: 0},
	{stage3_fruit2b: 0},
	{stage3_fruit3b: 0},
	{stage3_fruit4b: 0},
	{stage4_fruit1b: 0},
	{stage4_fruit2b: 0},
	{stage4_fruit3b: 0},
	{stage4_fruit4b: 0},
	{stage5_fruit1b: 0},
	{stage5_fruit2b: 0},
	{stage5_fruit3b: 0},
	{stage6_fruit1b: 0},
	{stage6_fruit2b: 0},
	{stage7_fruit1b: 0},
	{stage7_fruit2b: 0},
	{stage7_fruit3b: 0},
	{stage8_fruit1b: 0},
	{stage8_fruit2b: 0},
	{stage8_fruit3b: 0},
	{stage9_fruit1b: 0},
	{stage9_fruit2b: 0},
	{stage10_fruit1b: 0},
	{stage10_fruit2b: 0},
	{stage10_fruit3b: 0},
	{stage11_fruit1b: 0},
	{stage11_fruit2b: 0},
	{stage11_fruit3b: 0},
	{stage12_fruit1b: 0},
	{stage12_fruit2b: 0},
	{stage12_fruit3b: 0},
	{stage13_fruit1b: 0},
	{stage13_fruit2b: 0},
	{stage13_fruit3b: 0},
	{stage14_fruit1b: 0},
	{stage14_fruit2b: 0},
	{stage14_fruit3b: 0},
	{stage14_fruit4b: 0},
	{stage15_fruit1b: 0},
	{stage15_fruit2b: 0},
	{stage16_fruit1b: 0},
	{stage16_fruit2b: 0},
	{stage16_fruit3b: 0},
	{stage16_fruit4b: 0},
	{stage17_fruit1b: 0},
	{stage17_fruit2b: 0},
	{stage17_fruit3b: 0},
	{stage18_fruit1b: 0},
	{stage18_fruit2b: 0},
	{stage18_fruit3b: 0},
	{stage18_fruit4b: 0},
	{stage3_fruit3: 0},
	{stage3_fruit4: 0},
	{tag: 0},
	{stage4_fruit: 0},
	{stage4_fruit2: 0},
	{stage4_fruit3: 0},
	{stage4_fruit4: 0},
	{stage5_fruit: 0},
	{stage5_fruit2: 0},
	{stage5_fruit3: 0},
	{stage6_fruit: 0},
	{stage6_fruit2: 0},
	{stage7_fruit: 0},
	{stage7_fruit2: 0},
	{stage7_fruit3: 0},
	{stage8_fruit: 0},
	{stage8_fruit2: 0},
	{stage8_fruit3: 0},
	{stage9_fruit: 0},
	{stage9_fruit2: 0},
	{stage10_fruit: 0},
	{stage10_fruit2: 0},
	{stage10_fruit3: 0},
	{stage11_fruit: 0},
	{stage11_fruit2: 0},
	{stage11_fruit3: 0},
	{stage12_fruit: 0},
	{stage12_fruit2: 0},
	{stage12_fruit3: 0},
	{stage13_fruit: 0},
	{stage13_fruit2: 0},
	{stage13_fruit3: 0},
	{stage14_fruit: 0},
	{stage14_fruit2: 0},
	{stage14_fruit3: 0},
	{stage14_fruit4: 0},
	{stage15_fruit: 0},
	{stage15_fruit2: 0},
	{stage16_fruit: 0},
	{stage16_fruit2: 0},
	{stage16_fruit3: 0},
	{stage16_fruit4: 0},
	{stage17_fruit: 0},
	{stage17_fruit2: 0},
	{stage17_fruit3: 0},
	{stage18_fruit: 0},
	{stage18_fruit2: 0},
	{stage18_fruit3: 0},
	{stage18_fruit4: 0},
	{StarsText: 0},
	{Particles: 0},
	{Mouse: 0},
	{Button: 0},
	{Audio: 0}
];

self.InstanceType = {
	bg: class extends self.ISpriteInstance {},
	moreGames: class extends self.ISpriteInstance {},
	settingsIcon: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	audioOn: class extends self.ISpriteInstance {},
	fruity_world: class extends self.ISpriteInstance {},
	arcade_mode: class extends self.ISpriteInstance {},
	splashScreen: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	audioOff: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Button5: class extends self.IButtonInstance {},
	Text3: class extends self.ITextInstance {},
	Button2: class extends self.IButtonInstance {},
	ButtonNnn: class extends self.IButtonInstance {},
	Button123: class extends self.IButtonInstance {},
	Text4y: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	Text5: class extends self.ITextInstance {},
	Text6: class extends self.ITextInstance {},
	stage1: class extends self.ISpriteInstance {},
	stage2: class extends self.ISpriteInstance {},
	stage3: class extends self.ISpriteInstance {},
	stage4: class extends self.ISpriteInstance {},
	stage5: class extends self.ISpriteInstance {},
	stage6: class extends self.ISpriteInstance {},
	stage7: class extends self.ISpriteInstance {},
	stage8: class extends self.ISpriteInstance {},
	stage9: class extends self.ISpriteInstance {},
	stage10: class extends self.ISpriteInstance {},
	stage11: class extends self.ISpriteInstance {},
	stage12: class extends self.ISpriteInstance {},
	stage13: class extends self.ISpriteInstance {},
	stage14: class extends self.ISpriteInstance {},
	stage15: class extends self.ISpriteInstance {},
	stage16: class extends self.ISpriteInstance {},
	stage17: class extends self.ISpriteInstance {},
	stage18: class extends self.ISpriteInstance {},
	stage1_fruit: class extends self.ISpriteInstance {},
	stage1_fruit2: class extends self.ISpriteInstance {},
	stage1_fruit3: class extends self.ISpriteInstance {},
	stage1_fruit4: class extends self.ISpriteInstance {},
	stage2_fruit: class extends self.ISpriteInstance {},
	stage2_fruit2: class extends self.ISpriteInstance {},
	stage2_fruit3: class extends self.ISpriteInstance {},
	stage2_fruit4: class extends self.ISpriteInstance {},
	stage3_fruit: class extends self.ISpriteInstance {},
	stage3_fruit2: class extends self.ISpriteInstance {},
	stage1_fruit1b: class extends self.ISpriteInstance {},
	stage1_fruit2b: class extends self.ISpriteInstance {},
	stage1_fruit3b: class extends self.ISpriteInstance {},
	stage1_fruit4b: class extends self.ISpriteInstance {},
	stage2_fruit1b: class extends self.ISpriteInstance {},
	stage2_fruit2b: class extends self.ISpriteInstance {},
	stage2_fruit3b: class extends self.ISpriteInstance {},
	stage2_fruit4b: class extends self.ISpriteInstance {},
	stage3_fruit1b: class extends self.ISpriteInstance {},
	stage3_fruit2b: class extends self.ISpriteInstance {},
	stage3_fruit3b: class extends self.ISpriteInstance {},
	stage3_fruit4b: class extends self.ISpriteInstance {},
	stage4_fruit1b: class extends self.ISpriteInstance {},
	stage4_fruit2b: class extends self.ISpriteInstance {},
	stage4_fruit3b: class extends self.ISpriteInstance {},
	stage4_fruit4b: class extends self.ISpriteInstance {},
	stage5_fruit1b: class extends self.ISpriteInstance {},
	stage5_fruit2b: class extends self.ISpriteInstance {},
	stage5_fruit3b: class extends self.ISpriteInstance {},
	stage6_fruit1b: class extends self.ISpriteInstance {},
	stage6_fruit2b: class extends self.ISpriteInstance {},
	stage7_fruit1b: class extends self.ISpriteInstance {},
	stage7_fruit2b: class extends self.ISpriteInstance {},
	stage7_fruit3b: class extends self.ISpriteInstance {},
	stage8_fruit1b: class extends self.ISpriteInstance {},
	stage8_fruit2b: class extends self.ISpriteInstance {},
	stage8_fruit3b: class extends self.ISpriteInstance {},
	stage9_fruit1b: class extends self.ISpriteInstance {},
	stage9_fruit2b: class extends self.ISpriteInstance {},
	stage10_fruit1b: class extends self.ISpriteInstance {},
	stage10_fruit2b: class extends self.ISpriteInstance {},
	stage10_fruit3b: class extends self.ISpriteInstance {},
	stage11_fruit1b: class extends self.ISpriteInstance {},
	stage11_fruit2b: class extends self.ISpriteInstance {},
	stage11_fruit3b: class extends self.ISpriteInstance {},
	stage12_fruit1b: class extends self.ISpriteInstance {},
	stage12_fruit2b: class extends self.ISpriteInstance {},
	stage12_fruit3b: class extends self.ISpriteInstance {},
	stage13_fruit1b: class extends self.ISpriteInstance {},
	stage13_fruit2b: class extends self.ISpriteInstance {},
	stage13_fruit3b: class extends self.ISpriteInstance {},
	stage14_fruit1b: class extends self.ISpriteInstance {},
	stage14_fruit2b: class extends self.ISpriteInstance {},
	stage14_fruit3b: class extends self.ISpriteInstance {},
	stage14_fruit4b: class extends self.ISpriteInstance {},
	stage15_fruit1b: class extends self.ISpriteInstance {},
	stage15_fruit2b: class extends self.ISpriteInstance {},
	stage16_fruit1b: class extends self.ISpriteInstance {},
	stage16_fruit2b: class extends self.ISpriteInstance {},
	stage16_fruit3b: class extends self.ISpriteInstance {},
	stage16_fruit4b: class extends self.ISpriteInstance {},
	stage17_fruit1b: class extends self.ISpriteInstance {},
	stage17_fruit2b: class extends self.ISpriteInstance {},
	stage17_fruit3b: class extends self.ISpriteInstance {},
	stage18_fruit1b: class extends self.ISpriteInstance {},
	stage18_fruit2b: class extends self.ISpriteInstance {},
	stage18_fruit3b: class extends self.ISpriteInstance {},
	stage18_fruit4b: class extends self.ISpriteInstance {},
	stage3_fruit3: class extends self.ISpriteInstance {},
	stage3_fruit4: class extends self.ISpriteInstance {},
	stage4_fruit: class extends self.ISpriteInstance {},
	stage4_fruit2: class extends self.ISpriteInstance {},
	stage4_fruit3: class extends self.ISpriteInstance {},
	stage4_fruit4: class extends self.ISpriteInstance {},
	stage5_fruit: class extends self.ISpriteInstance {},
	stage5_fruit2: class extends self.ISpriteInstance {},
	stage5_fruit3: class extends self.ISpriteInstance {},
	stage6_fruit: class extends self.ISpriteInstance {},
	stage6_fruit2: class extends self.ISpriteInstance {},
	stage7_fruit: class extends self.ISpriteInstance {},
	stage7_fruit2: class extends self.ISpriteInstance {},
	stage7_fruit3: class extends self.ISpriteInstance {},
	stage8_fruit: class extends self.ISpriteInstance {},
	stage8_fruit2: class extends self.ISpriteInstance {},
	stage8_fruit3: class extends self.ISpriteInstance {},
	stage9_fruit: class extends self.ISpriteInstance {},
	stage9_fruit2: class extends self.ISpriteInstance {},
	stage10_fruit: class extends self.ISpriteInstance {},
	stage10_fruit2: class extends self.ISpriteInstance {},
	stage10_fruit3: class extends self.ISpriteInstance {},
	stage11_fruit: class extends self.ISpriteInstance {},
	stage11_fruit2: class extends self.ISpriteInstance {},
	stage11_fruit3: class extends self.ISpriteInstance {},
	stage12_fruit: class extends self.ISpriteInstance {},
	stage12_fruit2: class extends self.ISpriteInstance {},
	stage12_fruit3: class extends self.ISpriteInstance {},
	stage13_fruit: class extends self.ISpriteInstance {},
	stage13_fruit2: class extends self.ISpriteInstance {},
	stage13_fruit3: class extends self.ISpriteInstance {},
	stage14_fruit: class extends self.ISpriteInstance {},
	stage14_fruit2: class extends self.ISpriteInstance {},
	stage14_fruit3: class extends self.ISpriteInstance {},
	stage14_fruit4: class extends self.ISpriteInstance {},
	stage15_fruit: class extends self.ISpriteInstance {},
	stage15_fruit2: class extends self.ISpriteInstance {},
	stage16_fruit: class extends self.ISpriteInstance {},
	stage16_fruit2: class extends self.ISpriteInstance {},
	stage16_fruit3: class extends self.ISpriteInstance {},
	stage16_fruit4: class extends self.ISpriteInstance {},
	stage17_fruit: class extends self.ISpriteInstance {},
	stage17_fruit2: class extends self.ISpriteInstance {},
	stage17_fruit3: class extends self.ISpriteInstance {},
	stage18_fruit: class extends self.ISpriteInstance {},
	stage18_fruit2: class extends self.ISpriteInstance {},
	stage18_fruit3: class extends self.ISpriteInstance {},
	stage18_fruit4: class extends self.ISpriteInstance {},
	StarsText: class extends self.ITextInstance {},
	Particles: class extends self.IParticlesInstance {},
	Mouse: class extends self.IInstance {},
	Button: class extends self.IButtonInstance {},
	Audio: class extends self.IInstance {}
}